---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: config.json
  label: Site Info
- type: heading
  label: Content
- type: directory
  path: content/blog-posts
  label: Blog Posts
  create: documents
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_output_directory: public
  instant_preview_command: yarn dev
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
